Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace GibiSu.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        
    }
}

Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GibiSu.Data;
using GibiSu.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace GibiSu.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class MenusController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MenusController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Menus
        public async Task<IActionResult> Index()
        {
              return View(await _context.Menus.ToListAsync());
        }

        // GET: Menus/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.Menus == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // GET: Menus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(menu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(menu);
        }

        // GET: Menus/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.Menus == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus.FindAsync(id);
            if (menu == null)
            {
                return NotFound();
            }
            return View(menu);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, [Bind("Id,Name")] Menu menu)
        {
            if (id != menu.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(menu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuExists(menu.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(menu);
        }

        // GET: Menus/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null || _context.Menus == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            if (_context.Menus == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Menus'  is null.");
            }
            var menu = await _context.Menus.FindAsync(id);
            if (menu != null)
            {
                _context.Menus.Remove(menu);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuExists(short id)
        {
          return _context.Menus.Any(e => e.Id == id);
        }
    }
}

Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GibiSu.Data;
using GibiSu.Models;
using Microsoft.Extensions.Hosting;
using System.Security.Principal;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using System.Drawing.Imaging;
using System.IO;
using System.Reflection.Metadata;

namespace GibiSu.Controllers
{
    public class PagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        System.Drawing.Imaging.EncoderParameter qualityParameter;
        System.Drawing.Imaging.ImageCodecInfo[] allCoDecs;
        System.Drawing.Imaging.EncoderParameters encoderParameters;
        System.Drawing.Imaging.ImageCodecInfo jPEGCodec;
        System.Drawing.Image streamImage;
        System.Drawing.Image bLogImage;
        public PagesController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Pages
        public void kuki(string a)
        {
            if (a=="kabul")
            {
                var cookieOptions = new CookieOptions();
                cookieOptions.Expires = DateTime.Now.AddDays(1);
                cookieOptions.Path = "/";
                Response.Cookies.Append("isim1", "isim2", cookieOptions);
            }
            else if (a=="red")
            {
                var cookieOptions = new CookieOptions();
                cookieOptions.Path = "/#";
                Response.Cookies.Delete("isim1");
                
            }
        }

    public async Task<IActionResult> Index()
    {
        var applicationDbContext = _context.Pages.Include(p => p.Menu);
        Page page = _context.Pages.Include(p => p.Contents.OrderBy(c => c.Order)).Where(d => d.Url == "Index").FirstOrDefault();
        return View(page);
    }
       

        public async Task<IActionResult> Sayfalar()
    {
        var applicationDbContext = _context.Pages.Include(p => p.Menu);
        return View(await applicationDbContext.ToListAsync());
    }
        public async Task<PartialViewResult> NewContent(int i)
        {
            ViewData["contentCount"] = i;
            return PartialView();
        }

        public async Task<PartialViewResult> Preview([Bind("Url,FormImage,MenuId,Title,Contents")] Page page )
        {
            ViewData["pageName"] = Url;
            qualityParameter = new System.Drawing.Imaging.EncoderParameter(System.Drawing.Imaging.Encoder.Quality, 60L);
            allCoDecs = System.Drawing.Imaging.ImageCodecInfo.GetImageEncoders();
            encoderParameters = new System.Drawing.Imaging.EncoderParameters(1);
            foreach (System.Drawing.Imaging.ImageCodecInfo coDec in allCoDecs)
            {
                if (coDec.FormatDescription == "JPEG")
                {
                    jPEGCodec = coDec;
                }
            }
            ModelState.Remove("Banner");
            ModelState.Remove("Contents");

            //page.Contents[0].PageUrl=page.Url;
            MemoryStream memoryStream = new MemoryStream();
            encoderParameters.Param[0] = qualityParameter;
            if (page.FormImage != null)
            {
                page.FormImage.CopyTo(memoryStream);
                streamImage = System.Drawing.Image.FromStream(memoryStream);
                bLogImage = ReSize(streamImage, 1175, 540);
                bLogImage.Save(memoryStream, jPEGCodec, encoderParameters);
                if (ModelState.IsValid)
                {
                    page.Banner = memoryStream.ToArray();
                    foreach (Content content in page.Contents)
                    {
                        qualityParameter = new System.Drawing.Imaging.EncoderParameter(System.Drawing.Imaging.Encoder.Quality, 60L);
                        allCoDecs = System.Drawing.Imaging.ImageCodecInfo.GetImageEncoders();
                        encoderParameters = new System.Drawing.Imaging.EncoderParameters(1);
                        foreach (System.Drawing.Imaging.ImageCodecInfo coDec in allCoDecs)
                        {
                            if (coDec.FormatDescription == "JPEG")
                            {
                                jPEGCodec = coDec;
                            }
                        }

                        ModelState.Remove("Image");
                        MemoryStream memoryStream2 = new MemoryStream();
                        encoderParameters.Param[0] = qualityParameter;
                        if (content.FormImage != null)
                        {
                            content.FormImage.CopyTo(memoryStream2);
                            streamImage = System.Drawing.Image.FromStream(memoryStream2);
                            bLogImage = ReSize(streamImage, 435, 595);
                            bLogImage.Save(memoryStream2, jPEGCodec, encoderParameters);
                            //content.PageUrl = page.Url;
                            if (ModelState.IsValid)
                            {
                                content.Image = memoryStream2.ToArray();
                                //page.Contents.Add(content);
                            }
                        }

                        ViewData["PageUrl"] = new SelectList(_context.Pages, "Url", "Url", content.PageUrl);
                    }
                }
            }
            return PartialView(page);
        }

        // GET: Pages/Details/5
        public async Task<IActionResult> Details(string id)
    {
        ViewData["pageName"] = id;
        Page page = _context.Pages.Where(p => p.Url == id).Include(p => p.Contents.OrderBy(c => c.Order)).FirstOrDefault();
        if (id == null || _context.Pages == null)
        {
            return NotFound();
        }

        page = await _context.Pages
           .Include(p => p.Menu)
           .FirstOrDefaultAsync(m => m.Url == id);
        if (page == null)
        {
            return NotFound();
        }
            return View(page);
    }

        // GET: Pages/Create
    //[Authorize(Roles = "Administrator")]
    public IActionResult Create()
    {
        ViewData["MenuId"] = new SelectList(_context.Menus, "Id", "Name");
        return View();
    }

    // POST: Pages/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Url,FormImage,MenuId,Title,Contents")] Page page)
    {
            qualityParameter = new System.Drawing.Imaging.EncoderParameter(System.Drawing.Imaging.Encoder.Quality, 60L);
            allCoDecs = System.Drawing.Imaging.ImageCodecInfo.GetImageEncoders();
            encoderParameters = new System.Drawing.Imaging.EncoderParameters(1);
            foreach (System.Drawing.Imaging.ImageCodecInfo coDec in allCoDecs)
            {
                if (coDec.FormatDescription == "JPEG")
                {
                    jPEGCodec = coDec;
                }
            }
            ModelState.Remove("Banner");
        ModelState.Remove("Contents");

        MemoryStream memoryStream = new MemoryStream();
            encoderParameters.Param[0] = qualityParameter;
            if (page.FormImage != null)
            {
                page.FormImage.CopyTo(memoryStream);
                streamImage = System.Drawing.Image.FromStream(memoryStream);
                bLogImage = ReSize(streamImage, 1175, 540);
                bLogImage.Save(memoryStream, jPEGCodec, encoderParameters);
                if (ModelState.IsValid)
                {
                    page.Banner = memoryStream.ToArray();
                    if (page.Contents != null) {
                        foreach (Content content in page.Contents)
                        {
                            qualityParameter = new System.Drawing.Imaging.EncoderParameter(System.Drawing.Imaging.Encoder.Quality, 60L);
                            allCoDecs = System.Drawing.Imaging.ImageCodecInfo.GetImageEncoders();
                            encoderParameters = new System.Drawing.Imaging.EncoderParameters(1);
                            foreach (System.Drawing.Imaging.ImageCodecInfo coDec in allCoDecs)
                            {
                                if (coDec.FormatDescription == "JPEG")
                                {
                                    jPEGCodec = coDec;
                                }
                            }

                            ModelState.Remove("Image");
                            MemoryStream memoryStream2 = new MemoryStream();
                            encoderParameters.Param[0] = qualityParameter;
                            if (content.FormImage != null)
                            {
                                content.FormImage.CopyTo(memoryStream2);
                                streamImage = System.Drawing.Image.FromStream(memoryStream2);
                                bLogImage = ReSize(streamImage, 435, 595);
                                bLogImage.Save(memoryStream2, jPEGCodec, encoderParameters);
                                //content.PageUrl = page.Url;
                                if (ModelState.IsValid)
                                {
                                    content.Image = memoryStream2.ToArray();
                                    //page.Contents.Add(content);
                                }
                            }

                            ViewData["PageUrl"] = new SelectList(_context.Pages, "Url", "Url", content.PageUrl);
                        }
                    }
                    _context.Add(page);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }

Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
    
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GibiSu.styles.css" asp-append-version="true" />
    <link rel="icon" sizes="16x16" href="https://i.ibb.co/JtdRzwR/Whats-App-Image-2023-01-10-at-12-54-28-removebg-preview.png" />
    <link href="~/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" />
    <title>@ViewData["Title"]</title>
</head>
<body>
<div class="container-fluid">
    <div class="row" style="height:100vh;">
        <div class="list-group adminpanel col-2 border-end" >
            <h2><a  asp-controller="Admin" asp-action="Index" style="text-decoration: none;">Admin Paneli</a></h2>
            <hr />
            <div class="dropdown">
                <button class="btn btn-secondary btnAdmin dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Menüler
                </button>
                <ul class="dropdown-menu AdminUl" >
                    <li><a class="dropdown-item" asp-controller="Menus" asp-action="Create">Create</a>
                    <li> <a class="dropdown-item" asp-controller="Menus" asp-action="Index">Index</a>
                    </li>
                </ul>
            </div>
            <div class="dropdown">
                <button class="btn btn-secondary btnAdmin dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Sayfalar
                </button>
                <ul class="dropdown-menu AdminUl">
                    <li><a class="dropdown-item" asp-controller="Pages" asp-action="Create">Create</a>
                    <li> <a class="dropdown-item" asp-controller="Pages" asp-action="Sayfalar" >Index</a>
                    </li>
                </ul>
            </div>
            <div class="dropdown">
                <button class="btn btn-secondary btnAdmin dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    İçerikler
                </button>
                <ul class="dropdown-menu AdminUl">
                    <li><a class="dropdown-item" asp-controller="Contents" asp-action="Create">Create</a>
                    <li> <a class="dropdown-item" asp-controller="Contents" asp-action="Index">Index</a>
                    </li>
                </ul>
            </div>
            <div class="dropdown">
                <button class="btn btn-secondary btnAdmin dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Ürünler
                </button>
                <ul class="dropdown-menu AdminUl">
                    <li><a class="dropdown-item" asp-controller="Products" asp-action="Create">Create</a>
                    <li> <a class="dropdown-item" asp-controller="Products" asp-action="ProductsEdit">Index</a>
                    </li>
                </ul>
            </div>
            <div class="dropdown">
                <button class="btn btn-secondary btnAdmin dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Bekleyen Siparişler
                </button>
                <ul class="dropdown-menu AdminUl">
                    <li><a class="dropdown-item" asp-controller="Orders" asp-action="OrderTracking">Bekleyen Siparişler</a>
                    </li>
                </ul>
            </div>
             <div class="dropdown">
                <button class="btn btn-secondary btnAdmin dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Raporlar
                </button>
                <ul class="dropdown-menu AdminUl">
                    <li><a class="dropdown-item" asp-controller="OrderProducts" asp-action="SellingProducts">Sipariş Raporları</a>
                    </li>
                </ul>
            </div>
            <div class="dropdown">
                <a class="btn btn-secondary btnAdmin" type="button" href="/Users/Index" aria-expanded="false">
                   Üyeler
                </a>
            </div>
            <div class="dropdown">
                <a href="/Users/AdminList" class="btn btn-secondary btnAdmin" type="button" aria-expanded="false">
                    Kullanıcılar
                </a>
            </div>
                

            <i class="fa-solid fa-gear" style="bottom: 0; position: absolute; right: 0; font-size: 22px; margin-right: 5px; margin-bottom:5px;"></i>
            
            
        </div>
        <div class="col-10" style="position: absolute; right: 0; background-color:white;">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>

    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>