Models/OrderProduct.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GibiSu.Models
{
    public class OrderProduct
    {
        [Required(ErrorMessage = "Bu alan zorunludur.")]
        [DisplayName("Ürün")]
        public int ProductId { get; set; }

        [Required(ErrorMessage = "Bu alan zorunludur.")]
        [DisplayName("Sipariş Numarası")]
        public long OrderId { get; set; }

        [Required(ErrorMessage = "Bu alan zorunludur.")]
        [DisplayName("Adet")]
        public int Amount { get; set; }

        [DisplayName("Birim Fiyat")]
        public float Price { get; set; }

        [DisplayName("Toplam Fiyat")]
        public float TotalPrice { get; set; }

        [DisplayName("Ürün")]
        [ForeignKey("ProductId")]
        public Product? Product { get; set; }

        [DisplayName("Sipariş Numarası")]
        [ForeignKey("OrderId")]
        public Order? Order { get; set; }
    }
}

Controllers/OrderProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GibiSu.Data;
using GibiSu.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Authorization;

namespace GibiSu.Controllers
{
    [Authorize]
    public class OrderProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        UserManager<ApplicationUser> _userManager;

        public OrderProductsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: OrderProducts
        public async Task<IActionResult> Index()
        {
            string userName = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Product).Where(o => o.Order.OrderDate == null).Where(o => o.Order.UserId == userName);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<PartialViewResult> Reports(int? SelectProductId, string? SelectUser, DateTime? FirstOrderDate, DateTime? LastOrderDate)
        {
            //Seçili herhangi bir seçenek varsa
            if (SelectUser != "undefined" || SelectProductId != null || FirstOrderDate != null || LastOrderDate != null)
            {
                //Sadece Ürün Seçiliyse
                if (SelectProductId != null && SelectUser == "undefined" && FirstOrderDate == null && LastOrderDate == null) {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.ProductId == SelectProductId).Where(o=>o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Kullanıcı Seçiliyse
                if (SelectProductId == null && SelectUser != "undefined" && FirstOrderDate == null && LastOrderDate == null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.Order.UserId == SelectUser).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Başlangıç Tarihi Seçiliyse
                if (SelectProductId == null && SelectUser == "undefined" && FirstOrderDate != null && LastOrderDate == null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.Order.OrderDate >= FirstOrderDate).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Bitiş Tarihi Seçiliyse
                if (SelectProductId == null && SelectUser == "undefined" && FirstOrderDate == null && LastOrderDate != null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.Order.OrderDate <= LastOrderDate).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Kullanıcı ve Ürün Seçiliyse
                if (SelectProductId != null && SelectUser != "undefined" && FirstOrderDate == null && LastOrderDate == null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.Order.UserId == SelectUser).Where(o => o.ProductId == SelectProductId).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Kullanıcı ve Başlangıç Tarihi Seçiliyse
                if (SelectProductId == null && SelectUser != "undefined" && FirstOrderDate != null && LastOrderDate == null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.Order.UserId == SelectUser).Where(o => o.Order.OrderDate >= FirstOrderDate).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Kullanıcı ve Bitiş Tarihi Seçiliyse
                if (SelectProductId == null && SelectUser != "undefined" && FirstOrderDate == null && LastOrderDate != null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.Order.UserId == SelectUser).Where(o => o.Order.OrderDate <= LastOrderDate).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Ürün ve Başlangıç Tarihi Seçiliyse
                if (SelectProductId != null && SelectUser == "undefined" && FirstOrderDate != null && LastOrderDate == null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.ProductId == SelectProductId).Where(o => o.Order.OrderDate >= FirstOrderDate).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Ürün ve Bitiş Tarihi Seçiliyse
                if (SelectProductId != null && SelectUser == "undefined" && FirstOrderDate == null && LastOrderDate != null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.ProductId == SelectProductId).Where(o => o.Order.OrderDate <= LastOrderDate).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Başlangıç ve Bitiş Tarihi Seçiliyse
                if (SelectProductId == null && SelectUser == "undefined" && FirstOrderDate != null && LastOrderDate != null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.Order.OrderDate >= FirstOrderDate).Where(o => o.Order.OrderDate <= LastOrderDate).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Kullanıcı, Ürün, Başlangıç Tarihi Seçiliyse
                if (SelectProductId != null && SelectUser != "undefined" && FirstOrderDate != null && LastOrderDate == null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.Order.UserId == SelectUser).Where(o => o.ProductId == SelectProductId)
                        .Where(o => o.Order.OrderDate >= FirstOrderDate).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Kullanıcı, Ürün, Bitiş Tarihi Seçiliyse
                if (SelectProductId != null && SelectUser != "undefined" && FirstOrderDate == null && LastOrderDate != null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.Order.UserId == SelectUser).Where(o => o.ProductId == SelectProductId)
                        .Where(o => o.Order.OrderDate <= LastOrderDate).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Ürün, Başlangıç ve Bitiş Tarihi Seçiliyse
                if (SelectProductId != null && SelectUser == "undefined" && FirstOrderDate != null && LastOrderDate != null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.Order.OrderDate >= FirstOrderDate).Where(o => o.Order.OrderDate <= LastOrderDate)
                        .Where(o => o.ProductId == SelectProductId).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Kullanıcı, Başlangıç ve Bitiş Tarihi Seçiliyse
                if (SelectProductId == null && SelectUser != "undefined" && FirstOrderDate != null && LastOrderDate != null)
                {
                    var applicationDbContext = _context.OrderProducts.Include(o => o.Order).Include(o => o.Order.User)
                        .Where(o => o.Order.UserId == SelectUser).Where(o => o.Order.OrderDate <= LastOrderDate)
                        .Where(o => o.Order.OrderDate >= FirstOrderDate).Where(o => o.Order.OrderDate != null);
                    return PartialView(await applicationDbContext.ToListAsync());
                }
                //Sadece Kullanıcı, Ürün, Başlangıç ve Bitiş Tarihi Seçiliyse
                if (SelectProductId != null && SelectUser != "undefined" && FirstOrderDate != null && LastOrderDate != null)
                {

Views/OrderProducts/Create.cshtml
@model GibiSu.Models.OrderProduct

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>OrderProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/OrderProducts/Delete.cshtml
@model GibiSu.Models.OrderProduct

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderProduct</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Address)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/OrderProducts/Details.cshtml
@model GibiSu.Models.OrderProduct

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OrderProduct</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Address)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/OrderProducts/Edit.cshtml
@model GibiSu.Models.OrderProduct

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>OrderProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/OrderProducts/Index.cshtml
@model IEnumerable<GibiSu.Models.OrderProduct>
@using Microsoft.EntityFrameworkCore;
@{
    ViewData["Title"] = "Index";
    
    long orderId = Model.Select(o => o.OrderId).FirstOrDefault();
}
<script>
    function DeleteProduct(pid, oid) {
        $.get("@Url.Action("DeleteProduct","OrderProducts")?productid=" + pid + "&orderid=" + oid);
        setTimeout(
                  function() 
                  {
                document.location.reload();
                  }, 0151);
    }
    function CountUp(pid) {
        $.get("@Url.Action("CountPlus","OrderProducts")?productid=" + pid, function (pcount) {
            $("#PCount-" + pid).val(pcount);
            setTimeout(
                  function() 
                  {
                document.location.reload();
                }, 0151);
        });
    }
    function CountDown(pid) {
        $.get("@Url.Action("CountMinus","OrderProducts")?productid=" + pid, function (pcount) {
            $("#PCount-" + pid).val(pcount);
            setTimeout(
                function () {
                    document.location.reload();
                }, 0151);
        });
    }
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<h2 style="text-align:center;color:white;">Sepetim</h2>

<div class="container my-4">
    <div class="table">
        @foreach (var item in Model)
        {
            <div id="PCard-@item.ProductId.ToString()" class="order">
                <div class="order-header" style="justify-content: space-between;align-items: center;">
                    <div style="display:flex; align-items: center;">
                        <img src='data:image/jpeg;base64,@Convert.ToBase64String(item.Product.SmallImage)' class="card-img-top" style="width: 80px; height: 80px;margin-right: 20px;" />
                        <div style="font-size:17px;margin-right: 10px;" class="product-card-title">
                            @item.Product.Name
                        </div>
                    </div>
                    <div class="order-header-info" style="flex-direction:row;align-items:center;">
                        <div style= "margin-right: 10em;">
                            <button class="cart-count-btn btn btn-primary" onclick="CountDown(@item.ProductId)">
                                <i class="fa-solid fa-minus"></i>
                            </button>
                            <span>
                                <input disabled id="PCount-@item.ProductId.ToString()"
                                   type="number"
                                   style="width: 50px; border-radius: 10px" value="@item.Amount" />
                            </span>
                            <button class="cart-count-btn btn btn-primary" onclick="CountUp(@item.ProductId)">
                                <i class="fa-solid fa-plus"></i>
                            </button>
                        </div>
                        <div style="color:#0d6efd;margin-right: 10em;">
                       @item.TotalPrice TL
                    </div>
                        <div style="">
                            <span>
                                <button onclick="DeleteProduct(@item.ProductId,@item.OrderId)" class="cart-count-btn btn btn-primary">
                                    <i class="fa fa-trash-o"  style="font-size: 13px;"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div style="text-align: center">
    @if (orderId != 0)
    {
        <span>
            <button onclick="location.href='/orders/edit/@orderId'" class="button-card-cart btn btn-primary">
            <i class="fa-solid fa-cart-shopping"></i> Sepeti Onayla
        </button>
    </span>}
</div>

Views/OrderProducts/Reports.cshtml
@model IEnumerable<GibiSu.Models.OrderProduct>
@using Microsoft.EntityFrameworkCore;
@using GibiSu.Data;
@inject ApplicationDbContext context;

@{
    var products = context.Products;
    float totalPrice = 0;
    float totalLitre = 0;
}

@if (Model.Count() == 0)
{
    <div>
        Sonuç Bulunamadı!
    </div>
}
@if (Model.Count() != 0)
{
    <thead style="text-align: start;">
        <tr>
            <th style="padding-left:5%;">@Html.DisplayNameFor(model => model.Order.OrderDate)</th>
            <th>@Html.DisplayNameFor(model => model.Order.User.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Product.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Amount)</th>
            <th style="text-align: end;padding-right:5%;">@Html.DisplayNameFor(model => model.TotalPrice)</th>
        </tr>
    </thead>
    <tbody class="Order" style="text-align: start;">
    @foreach (var item in Model)
{
    @foreach (var item3 in products)
    {
        @if (item.ProductId == item3.Id)
        {
            <tr style="color:white;margin-bottom: 10px;">
                
                <td style="width: 25%;padding-left:5%;">
                    @Html.DisplayFor(modelItem => item.Order.OrderDate)
                </td>
                <td style="width: 20%;">
                        @Html.DisplayFor(modelItem => item.Order.User.Name)
                </td>
                <td style="width: 25%;">
                     @Html.DisplayFor(modelItem => item3.Name)
                </td>

                <td style=" width: 10%;color:white;">
                    X @item.Amount
                </td>
                <td style="text-align:end; width: 20%;color:white;padding-right:5%;">
                    <strong>@item.TotalPrice TL</strong>
                </td>

            </tr>
        }
    } 
}
        <tr style="border-color:#215fac">
            <td style=" width: 25%;padding-left:5%;color:white;">
             </td>

            <td style=" width: 20%;color:white;">
            </td>

            <td style="width: 25%;">
               
            </td>

            <td style=" width: 10%;color:white;">
            </td>

            <td style="padding-right:5%;text-align: end; color:black; width: 20%; background-color:white;">
                @foreach (var item in Model)
                {
                     totalPrice += item.TotalPrice;
                }
                Genel Toplam: <strong>@totalPrice.ToString() TL</strong>
                
            </td>
        </tr>
        <tr style="border-color:#215fac">
            <td style=" width: 25%;padding-left:5%;color:white;">
            </td>

            <td style=" width: 20%;color:white;">
            </td>

            <td style="width: 25%;">
               
            </td>

            <td style=" width: 10%;color:white;">
            </td>

            <td style="padding-right:5%;text-align: end; color:black; width: 20%; background-color:white;">
                @foreach (var item in Model)
                {
                    totalLitre += item.Product.Volume;
                }
                @totalLitre.ToString() L

            </td>
        </tr>
 </tbody>
 }

Views/OrderProducts/SellingProducts.cshtml
@model IEnumerable<GibiSu.Models.OrderProduct>
@using Microsoft.AspNetCore.Identity;
@using Microsoft.EntityFrameworkCore;
@using GibiSu.Data;
@inject ApplicationDbContext context;
@inject SignInManager<ApplicationUser> _signInManager;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var products = context.Products;

    var users = _signInManager.UserManager.Users;
    
}
<script>
    function GetSellingProduct(){
        var selectP = $('#SelectedProduct').val();
        var selectProduct = $('#SelectedP [value="' + selectP + '"]').data('value');
        var selectU = $('#SelectedUser').val();
        var selectUser = $('#SelectedU [value="' + selectU + '"]').data('value');
        var inputFirstDate = document.getElementById("FirstDate").value;
        var inputLastDate = document.getElementById("LastDate").value;
        $("#GetReport").load("@Url.Action("Reports","OrderProducts")?SelectProductId=" + selectProduct + "&SelectUser=" + selectUser + "&FirstOrderDate=" + inputFirstDate + "&LastOrderDate=" + inputLastDate);
    }
</script>
<h1 style="text-align:center;color:black;margin-bottom:50px;">Rapor</h1>
<div class="">
    <div class="">
        <form enctype="multipart/form-data">
            <div style="margin-bottom:15px;" class="form-group">
                <input id="SelectedProduct" class="form-control" type="text" list="SelectedP" placeholder="Ürün Adını Giriniz..." />
                <datalist id="SelectedP" >
                    @foreach (var item3 in products)
                    {
                        <option data-value="@item3.Id" value="@item3.Name" class="form-control"></option>
                    }
                </datalist>
            </div>
            <div class="form-group">
                <input id="SelectedUser" class="form-control" type="text" list="SelectedU" placeholder="Müşteri Adını Giriniz..." />
                <datalist id="SelectedU" >
                    @foreach (var item3 in users)
                    {
                        <option data-value="@item3.Id" value="@item3.Name" class="form-control"> </option>
                    }
                </datalist>
            </div>
            <div class="form-group">
                <label class="control-label">Başlangıç Tarihi</label>
                <input id="FirstDate" type="date" class="form-control" />
                <span class="text-danger"></span>
                <label class="control-label">Bitiş Tarihi</label>
                <input id="LastDate" type="date" class="form-control" />
                <span class="text-danger"></span>
            </div>
            <div style="margin-top:15px;" class="form-group">
                <input onclick="GetSellingProduct()"  type="button" value="Raporu Getir" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<table class="table" id="GetReport">
   
</table>